Bug fixes for TTO
slaclab/Badger pull request #28
Opened 2024-03-15 08:33 UTC by wenatuhs

### Bug fixes

- Fix the cannot-delete-last-run issue
- Support constraints/states in routine editor
- Auto-select the updated routine in the routine list once the changes are saved

### Remaining issues

- Critical constraints being triggered incorrectly (Xopt-related)
- Possible faulty behavior when add constraints in routine

2024-03-15 14:01 UTC, roussel-ryan requested changes
Mostly looks good, some minor comments to address

2024-03-15 14:01 UTC, roussel-ryan commented on src/badger/gui/default/components/routine_page.py
> +        states = []
can we rename `states` variables in Badger to observables such that it is consistent with Xopt? or do they mean something different?

2024-03-15 14:01 UTC, roussel-ryan commented on src/badger/gui/default/components/run_monitor.py
> +            return None
are we sure we want to return None here? I suggest that we raise an error saying that not routine has been specified instead. Might be easier for the user to debug

2024-03-15 14:01 UTC, roussel-ryan commented on src/badger/gui/default/components/run_monitor.py
> +                    self.monitor, "states", 'Evaluation History (S)',
relevant to the states question above

2024-03-18 18:54 UTC, wenatuhs commented on src/badger/gui/default/components/routine_page.py
> +        states = []
Sure thing! They mean the same, the concern was that the observables here get confused with the observables in Badger env, but maybe I'm overthinking

2024-03-18 18:57 UTC, wenatuhs commented on src/badger/gui/default/components/run_monitor.py
> +            return None
It's a valid status that the run monitor doesn't hold a routine -- say when the user just gets started and creates a few routines without running them, in this case, if the user doesn’t select any routine in the list the run monitor should be in this empty status

2024-03-18 18:57 UTC, wenatuhs commented on src/badger/gui/default/components/run_monitor.py
> +                    self.monitor, "states", 'Evaluation History (S)',
Will change to `plot_obs`!

2024-03-20 14:20 UTC, roussel-ryan approved these changes

2024-03-20 15:03 UTC, merged